from setuptools import setup, find_packages

setup(
    name='slavian_market_bot',
    version='1.0.0',
    author='Dmitry Brykin',
    author_email='red_r2005@mail.ru',
    description='This is a sample package',
    long_description='Long description of the package',
    long_description_content_type='text/markdown',
    url='https://github.com/Dmitry-Crimea/trade-house.git',
    packages=find_packages(),
    install_requires=[
        'aiofiles==23.2.1',
        'aiogram==3.4.1',
        'aiohttp==3.9.5',
        'aiosignal==1.3.1',
        'aiosqlite==0.20.0',
        'annotated-types==0.6.0',
        'async-timeout==4.0.3',
        'attrs==23.2.0',
        'certifi==2024.2.2',
        'frozenlist==1.4.1',
        'greenlet==3.0.3',
        'idna==3.7',
        'magic-filter==1.0.12',
        'multidict==6.0.5',
        'pydantic==2.5.3',
        'pydantic_core==2.14.6',
        'SQLAlchemy==2.0.29',
        'typing_extensions==4.11.0',
        'yarl==1.9.4',
    ],
)
