---

- name: Copy ssh private_key
  copy:
    src: "{{ ssh.local_path_to_ssh_pvt_key }}"
    dest: "{{ git.home_dir }}/{{ git.user }}/{{ ssh.remote_path_to_ssh_pvt_key }}"
    
- name: Make workdir in remote host
  file:
    path: "{{ remote_host.work_dir }}"
    state: directory

- name: Clone repository
  git:
    repo: "{{ git.repo }}"
    dest: "{{ remote_host.work_dir }}"
