####################################################
#        Параметры Микросервиса
####################################################
config_properties:
  BOT_ENGINE: 'sqlite+aiosqlite:///db.sqlite3'


####################################################
#        Параметры Ingress
####################################################
ingress:
  enabled: true
  env: "na"
  
####################################################
#        Параметры POD
# Ресурсы необходимые для корректной работы
# микросервиса
####################################################
REGISTRY_URL: "cr.yandex/crpmt87l8a5g34cek6lc/main:1.0.0" # Хранилище образа микросервиса
NAMESPACE: "dk5-test-test-env" # Namespace в системе оркестрации
HOST: "test.ru" # Домен контура, в котором работает микросервис
replicas: 1
APP_PORT: 8090
APP_CPU_LIMIT: 500m
APP_MEMORY_LIMIT: 1000Mi
APP_MEMORY_REQ: 500Mi
APP_CPU_REQ: 250m
MAX_UNAVAILABLE: 0
MAX_SURGE: 1

####################################################
#                  Параметры HPA
# Значение "true" включит горизонтальное
# масштабирование
####################################################
horizontalPodAutoscaler:
  enabled: false
